steps:

- id: "Rodando docker-compose"
  name: "gcr.io/$PROJECT_ID/docker-compose"
  args: [ '-f', 'docker-compose.yaml', 'up', '-d']

- id: "Rodando teste unitário"
  name: "gcr.io/cloud-builders/go"
  args: ['test']
  env: ['GOPATH=.']

- id: "Salvando imagem no GCR"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go', '.']

images:
  - 'gcr.io/$PROJECT_ID/go'

