steps:

- id: "Rodando docker-compose"
  name: "gcr.io/$PROJECT_ID/docker-compose"
  args: [ '-f', 'docker-compose.yaml', 'up', '-d']

- id: "Salvando imagem no GCR"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/golang', '.']

images:
  - 'gcr.io/$PROJECT_ID/go:1.13.1-stretch'

